"""Export a selection of datasets to a runnable marimo app or a Colab notebook.

Both artifacts are self-contained: they ``pip install`` psidata, fetch the exact source files by
URL, parse them with the same readers, and rebuild an equivalent Plotly figure. This makes the
"Open in marimo / Colab" feature reproducible rather than a screenshot.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

import nbformat

#: Package spec the generated notebooks install. Override once psidata is published to PyPI or
#: pin to a git URL, e.g. "psidata @ git+https://github.com/yargerlab/psidata".
PACKAGE_SPEC = "psidata"


@dataclass(frozen=True)
class ExportItem:
    """One dataset to reproduce: a display name, the raw URL, and the technique hint."""

    name: str
    url: str
    technique: str | None = None


def _items_literal(items: list[ExportItem]) -> str:
    return json.dumps([[it.name, it.url, it.technique] for it in items], indent=4)


# --- shared body that loads + plots, embedded into both artifacts -----------------------------
def _plot_body(items: list[ExportItem], x_quantity: str) -> str:
    return f'''import httpx
import plotly.graph_objects as go
from psidata import Candidate, read

# (display name, raw file URL, technique hint) for each selected dataset
DATASETS = {_items_literal(items)}
X_QUANTITY = {x_quantity!r}  # "temperature" or "time" (DSC only)


def load(name, url, technique):
    text = httpx.get(url, follow_redirects=True, timeout=60).text
    return read(Candidate(filename=name, text=text, uri=url, technique_hint=technique))


def x_column(signal):
    if X_QUANTITY == "time":
        for col in signal.frame.columns:
            if "time" in col.lower():
                return col
    return signal.x.label


fig = go.Figure()
x_title = y_title = ""
reverse_x = False
for name, url, technique in DATASETS:
    ds = load(name, url, technique)
    sample = ds.metadata.sample_name or name
    if ds.technique in ("NMR", "FTIR"):
        reverse_x = True  # NMR/FTIR convention: abscissa decreases left->right
    for sig in ds.signals:
        x_title, y_title = sig.x.title, sig.y.title
        fig.add_scatter(
            x=sig.frame[x_column(sig)], y=sig.frame[sig.y.label], mode="lines",
            name=f"{{sample}} · {{sig.segment or sig.name}}",
        )
fig.update_layout(template="plotly_white", xaxis_title=x_title, yaxis_title=y_title,
                  legend_title="Dataset")
if reverse_x:
    fig.update_xaxes(autorange="reversed")
fig'''


def to_marimo(items: list[ExportItem], x_quantity: str = "temperature") -> str:
    """Return the source of a runnable marimo app (``.py``) reproducing the figure."""
    body = _plot_body(items, x_quantity)
    indented = "\n".join("    " + line if line else "" for line in body.splitlines())
    return f'''import marimo

app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    mo.md("# PsiData export\\n\\nInteractive view of {len(items)} dataset(s). Run all cells.")
    return (mo,)


@app.cell
def _():
{indented}


if __name__ == "__main__":
    app.run()
'''


def to_colab(items: list[ExportItem], x_quantity: str = "temperature") -> bytes:
    """Return a Colab/Jupyter notebook (``.ipynb`` bytes) reproducing the figure."""
    nb = nbformat.v4.new_notebook()
    nb.cells = [
        nbformat.v4.new_markdown_cell(
            "# PsiData export\n\n"
            f"Interactive view of {len(items)} dataset(s), generated by PsiData. "
            "Run the cells top to bottom."
        ),
        nbformat.v4.new_code_cell(f"!pip install -q {PACKAGE_SPEC} plotly httpx"),
        nbformat.v4.new_code_cell(_plot_body(items, x_quantity)),
    ]
    nb.metadata["language_info"] = {"name": "python"}
    return nbformat.writes(nb).encode("utf-8")
